@startuml
!include <C4/C4_Container>

LAYOUT_TOP_DOWN()

Person(student, "Student", "Vult tentamen in")
Person(docent, "Docent", "Beheert tentamen")
Person(admin, "Admin", "Beheert platform")

System_Boundary(webApp, "Web App") {
    Container(webAppInterface, "Gebruikersinterface", "Biedt gebruikers interface aan", "ReactJS")
}



System_Boundary(TripApp, "Triptop Applicatie") {


}

System(apiGateway, "API Gateway", "Stuurt requests door, Secure door toegang", "Node.js / Express")
System(backend, "Backend", "Behandelt alle gegevens", "Spring Boot / Java")
System(database, "Database", "Slaat data op, Haalt gegevens op", "MySQL")
System(identityProvider, "Identity Provider", "Gebruikt extern systeem voor authenticatie", "OAuth2 / JWT")
System(adminApp, "Admin Applicatie", "Beheert platform", "ReactJS")

Rel(student, webAppInterface, "Gebruikt")
Rel(docent, webAppInterface, "Beheert tentamen")
Rel(webAppInterface, apiGateway, "Verstuurt API requests")
Rel(apiGateway, backend, "Doorstuurt verzoeken")
Rel(backend, database, "Haalt gegevens op / Slaat gegevens op")
Rel(backend, identityProvider, "Gebruikt voor authenticatie")
Rel(backend, schoolyear, "Zet en haalt schooljaar gegevens op")
Rel(admin, adminApp, "Beheert platform")
Rel(adminApp, apiGateway, "Verstuurt beheer verzoeken")
Rel(apiGateway, backend, "Behandelt platformbeheer")
Rel(identityProvider, backend, "Verwerkt authenticatie")

System_Ext(smsProvider, "SMS Provider", "Verzendt sms berichten", "Twilio")
Rel(backend, smsProvider, "Verstuurt notificaties via SMS")

@enduml
